includes:
  - base.yaml
pipeline: GALAPipeline
con_model: ERM
model:
  model_name: GALAvGIN
ood:
  ood_alg: GALA
  ood_param: 0.8
  extra_param:
    - 2
    - 0.5
train:
  max_epoch: 200
  lr: 0.001
  weight_decay: 0.0
log_file: exp_0
clean_save: true
