includes:
  - base.yaml
model:
  model_name: LECIvGIN
ood:
  ood_alg: LECI
  ood_param: 1.0
  extra_param:
    - 1
    - 0
    - 0.1
    - 90
    - 0.1
    - true
train:
  max_epoch: 200
  lr: 0.0001
  pre_train: 20
  weight_decay: 0.0001
log_file: case_study
clean_save: true
