includes:
  - base.yaml
pipeline: GALAPipeline
con_model: ERM
model:
  model_name: GALAvGIN
ood:
  ood_alg: GALA
  ood_param: 0.6
  extra_param:
    - 4
    - 1
train:
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 300
  weight_decay: 0.0
log_file: exp_0
clean_save: true
